// Generated by gencpp from file mpc_local_planner_msgs/StateFeedback.msg
// DO NOT EDIT!


#ifndef MPC_LOCAL_PLANNER_MSGS_MESSAGE_STATEFEEDBACK_H
#define MPC_LOCAL_PLANNER_MSGS_MESSAGE_STATEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mpc_local_planner_msgs
{
template <class ContainerAllocator>
struct StateFeedback_
{
  typedef StateFeedback_<ContainerAllocator> Type;

  StateFeedback_()
    : header()
    , state()  {
    }
  StateFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StateFeedback_

typedef ::mpc_local_planner_msgs::StateFeedback_<std::allocator<void> > StateFeedback;

typedef boost::shared_ptr< ::mpc_local_planner_msgs::StateFeedback > StateFeedbackPtr;
typedef boost::shared_ptr< ::mpc_local_planner_msgs::StateFeedback const> StateFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator1> & lhs, const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator1> & lhs, const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpc_local_planner_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0230db5ba6622f6ac5c5440d8325e69";
  }

  static const char* value(const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0230db5ba6622f6ULL;
  static const uint64_t static_value2 = 0xac5c5440d8325e69ULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc_local_planner_msgs/StateFeedback";
  }

  static const char* value(const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64[] state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc_local_planner_msgs::StateFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_LOCAL_PLANNER_MSGS_MESSAGE_STATEFEEDBACK_H
