//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mpc_local_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mpc_local_planner__CONTROLLERRECONFIGURECONFIG_H__
#define __mpc_local_planner__CONTROLLERRECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mpc_local_planner
{
  class ControllerReconfigureConfigStatics;

  class ControllerReconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ControllerReconfigureConfig &config, const ControllerReconfigureConfig &max, const ControllerReconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ControllerReconfigureConfig &config1, const ControllerReconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ControllerReconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ControllerReconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControllerReconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControllerReconfigureConfig &config) const = 0;
      virtual void getValue(const ControllerReconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ControllerReconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ControllerReconfigureConfig::* field;

      virtual void clamp(ControllerReconfigureConfig &config, const ControllerReconfigureConfig &max, const ControllerReconfigureConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ControllerReconfigureConfig &config1, const ControllerReconfigureConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ControllerReconfigureConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ControllerReconfigureConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControllerReconfigureConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControllerReconfigureConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ControllerReconfigureConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ControllerReconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ControllerReconfigureConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ControllerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class CONTROLLER
{
  public:
    CONTROLLER()
    {
      state = true;
      name = "Controller";
    }

    void setParams(ControllerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("xy_goal_tolerance"==(*_i)->name){xy_goal_tolerance = boost::any_cast<double>(val);}
        if("yaw_goal_tolerance"==(*_i)->name){yaw_goal_tolerance = boost::any_cast<double>(val);}
        if("global_plan_overwrite_orientation"==(*_i)->name){global_plan_overwrite_orientation = boost::any_cast<bool>(val);}
        if("global_plan_prune_distance"==(*_i)->name){global_plan_prune_distance = boost::any_cast<double>(val);}
        if("max_global_plan_lookahead_dist"==(*_i)->name){max_global_plan_lookahead_dist = boost::any_cast<double>(val);}
        if("global_plan_viapoint_sep"==(*_i)->name){global_plan_viapoint_sep = boost::any_cast<double>(val);}
      }
    }

    double xy_goal_tolerance;
double yaw_goal_tolerance;
bool global_plan_overwrite_orientation;
double global_plan_prune_distance;
double max_global_plan_lookahead_dist;
double global_plan_viapoint_sep;

    bool state;
    std::string name;

    
}controller;

}groups;



//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      double xy_goal_tolerance;
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      double yaw_goal_tolerance;
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      bool global_plan_overwrite_orientation;
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      double global_plan_prune_distance;
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      double max_global_plan_lookahead_dist;
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      double global_plan_viapoint_sep;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ControllerReconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ControllerReconfigureConfig &__max__ = __getMax__();
      const ControllerReconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ControllerReconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ControllerReconfigureConfig &__getDefault__();
    static const ControllerReconfigureConfig &__getMax__();
    static const ControllerReconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ControllerReconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ControllerReconfigureConfig::ParamDescription<std::string>::clamp(ControllerReconfigureConfig &config, const ControllerReconfigureConfig &max, const ControllerReconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ControllerReconfigureConfigStatics
  {
    friend class ControllerReconfigureConfig;

    ControllerReconfigureConfigStatics()
    {
ControllerReconfigureConfig::GroupDescription<ControllerReconfigureConfig::DEFAULT, ControllerReconfigureConfig> Default("Default", "", 0, 0, true, &ControllerReconfigureConfig::groups);
ControllerReconfigureConfig::GroupDescription<ControllerReconfigureConfig::DEFAULT::CONTROLLER, ControllerReconfigureConfig::DEFAULT> Controller("Controller", "tab", 0, 1, true, &ControllerReconfigureConfig::DEFAULT::controller);
//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.xy_goal_tolerance = 0.0;
//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.xy_goal_tolerance = 1.0;
//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.xy_goal_tolerance = 0.2;
//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Allowed final euclidean distance to the goal position", "", &ControllerReconfigureConfig::xy_goal_tolerance)));
//#line 20 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("xy_goal_tolerance", "double", 0, "Allowed final euclidean distance to the goal position", "", &ControllerReconfigureConfig::xy_goal_tolerance)));
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.yaw_goal_tolerance = 0.0;
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.yaw_goal_tolerance = 1.0;
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.yaw_goal_tolerance = 0.1;
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Allowed final orientation error to the goal orientation", "", &ControllerReconfigureConfig::yaw_goal_tolerance)));
//#line 22 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("yaw_goal_tolerance", "double", 0, "Allowed final orientation error to the goal orientation", "", &ControllerReconfigureConfig::yaw_goal_tolerance)));
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.global_plan_overwrite_orientation = 0;
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.global_plan_overwrite_orientation = 1;
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.global_plan_overwrite_orientation = 1;
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<bool>("global_plan_overwrite_orientation", "bool", 0, "Some global planners are not considering the orientation at local subgoals between start and global goal, therefore determine it automatically", "", &ControllerReconfigureConfig::global_plan_overwrite_orientation)));
//#line 24 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<bool>("global_plan_overwrite_orientation", "bool", 0, "Some global planners are not considering the orientation at local subgoals between start and global goal, therefore determine it automatically", "", &ControllerReconfigureConfig::global_plan_overwrite_orientation)));
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.global_plan_prune_distance = 0.0;
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.global_plan_prune_distance = 10.0;
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.global_plan_prune_distance = 1.0;
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("global_plan_prune_distance", "double", 0, "", "", &ControllerReconfigureConfig::global_plan_prune_distance)));
//#line 26 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("global_plan_prune_distance", "double", 0, "", "", &ControllerReconfigureConfig::global_plan_prune_distance)));
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.max_global_plan_lookahead_dist = 0.0;
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.max_global_plan_lookahead_dist = 10.0;
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.max_global_plan_lookahead_dist = 1.5;
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("max_global_plan_lookahead_dist", "double", 0, "Specify maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization [if 0 or negative: disabled; the length is also bounded by the local costmap size]", "", &ControllerReconfigureConfig::max_global_plan_lookahead_dist)));
//#line 28 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("max_global_plan_lookahead_dist", "double", 0, "Specify maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization [if 0 or negative: disabled; the length is also bounded by the local costmap size]", "", &ControllerReconfigureConfig::max_global_plan_lookahead_dist)));
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __min__.global_plan_viapoint_sep = -1.0;
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __max__.global_plan_viapoint_sep = 10.0;
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __default__.global_plan_viapoint_sep = -1.0;
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      Controller.abstract_parameters.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("global_plan_viapoint_sep", "double", 0, "Min. separation between each two consecutive via-points extracted from the global plan [if negative: disabled]", "", &ControllerReconfigureConfig::global_plan_viapoint_sep)));
//#line 30 "/home/thefakhreddin/turtlebot_gazebo/src/mpc_local_planner/mpc_local_planner/cfg/mpc_controller.cfg"
      __param_descriptions__.push_back(ControllerReconfigureConfig::AbstractParamDescriptionConstPtr(new ControllerReconfigureConfig::ParamDescription<double>("global_plan_viapoint_sep", "double", 0, "Min. separation between each two consecutive via-points extracted from the global plan [if negative: disabled]", "", &ControllerReconfigureConfig::global_plan_viapoint_sep)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Controller.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr(new ControllerReconfigureConfig::GroupDescription<ControllerReconfigureConfig::DEFAULT::CONTROLLER, ControllerReconfigureConfig::DEFAULT>(Controller)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr(new ControllerReconfigureConfig::GroupDescription<ControllerReconfigureConfig::DEFAULT::CONTROLLER, ControllerReconfigureConfig::DEFAULT>(Controller)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr(new ControllerReconfigureConfig::GroupDescription<ControllerReconfigureConfig::DEFAULT, ControllerReconfigureConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ControllerReconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ControllerReconfigureConfig __max__;
    ControllerReconfigureConfig __min__;
    ControllerReconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ControllerReconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ControllerReconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ControllerReconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ControllerReconfigureConfig &ControllerReconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ControllerReconfigureConfig &ControllerReconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ControllerReconfigureConfig &ControllerReconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ControllerReconfigureConfig::AbstractParamDescriptionConstPtr> &ControllerReconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ControllerReconfigureConfig::AbstractGroupDescriptionConstPtr> &ControllerReconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ControllerReconfigureConfigStatics *ControllerReconfigureConfig::__get_statics__()
  {
    const static ControllerReconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ControllerReconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CONTROLLERRECONFIGURERECONFIGURATOR_H__
