// Generated by gencpp from file rigid2d/set_pose.msg
// DO NOT EDIT!


#ifndef RIGID2D_MESSAGE_SET_POSE_H
#define RIGID2D_MESSAGE_SET_POSE_H

#include <ros/service_traits.h>


#include <rigid2d/set_poseRequest.h>
#include <rigid2d/set_poseResponse.h>


namespace rigid2d
{

struct set_pose
{

typedef set_poseRequest Request;
typedef set_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_pose
} // namespace rigid2d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rigid2d::set_pose > {
  static const char* value()
  {
    return "c5432c85aa30571647ef4a6b0e1b56d9";
  }

  static const char* value(const ::rigid2d::set_pose&) { return value(); }
};

template<>
struct DataType< ::rigid2d::set_pose > {
  static const char* value()
  {
    return "rigid2d/set_pose";
  }

  static const char* value(const ::rigid2d::set_pose&) { return value(); }
};


// service_traits::MD5Sum< ::rigid2d::set_poseRequest> should match
// service_traits::MD5Sum< ::rigid2d::set_pose >
template<>
struct MD5Sum< ::rigid2d::set_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rigid2d::set_pose >::value();
  }
  static const char* value(const ::rigid2d::set_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rigid2d::set_poseRequest> should match
// service_traits::DataType< ::rigid2d::set_pose >
template<>
struct DataType< ::rigid2d::set_poseRequest>
{
  static const char* value()
  {
    return DataType< ::rigid2d::set_pose >::value();
  }
  static const char* value(const ::rigid2d::set_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rigid2d::set_poseResponse> should match
// service_traits::MD5Sum< ::rigid2d::set_pose >
template<>
struct MD5Sum< ::rigid2d::set_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rigid2d::set_pose >::value();
  }
  static const char* value(const ::rigid2d::set_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rigid2d::set_poseResponse> should match
// service_traits::DataType< ::rigid2d::set_pose >
template<>
struct DataType< ::rigid2d::set_poseResponse>
{
  static const char* value()
  {
    return DataType< ::rigid2d::set_pose >::value();
  }
  static const char* value(const ::rigid2d::set_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIGID2D_MESSAGE_SET_POSE_H
