// Generated by gencpp from file rigid2d/set_poseRequest.msg
// DO NOT EDIT!


#ifndef RIGID2D_MESSAGE_SET_POSEREQUEST_H
#define RIGID2D_MESSAGE_SET_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rigid2d
{
template <class ContainerAllocator>
struct set_poseRequest_
{
  typedef set_poseRequest_<ContainerAllocator> Type;

  set_poseRequest_()
    : theta(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  set_poseRequest_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_type;
  _theta_type theta;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::rigid2d::set_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rigid2d::set_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_poseRequest_

typedef ::rigid2d::set_poseRequest_<std::allocator<void> > set_poseRequest;

typedef boost::shared_ptr< ::rigid2d::set_poseRequest > set_poseRequestPtr;
typedef boost::shared_ptr< ::rigid2d::set_poseRequest const> set_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rigid2d::set_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rigid2d::set_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rigid2d::set_poseRequest_<ContainerAllocator1> & lhs, const ::rigid2d::set_poseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rigid2d::set_poseRequest_<ContainerAllocator1> & lhs, const ::rigid2d::set_poseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rigid2d

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rigid2d::set_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rigid2d::set_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rigid2d::set_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rigid2d::set_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rigid2d::set_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rigid2d::set_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rigid2d::set_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "245ce98f734504fd1235e73576484de3";
  }

  static const char* value(const ::rigid2d::set_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x245ce98f734504fdULL;
  static const uint64_t static_value2 = 0x1235e73576484de3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rigid2d::set_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rigid2d/set_poseRequest";
  }

  static const char* value(const ::rigid2d::set_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rigid2d::set_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# sets pose of robot\n"
"# theta (angular position) x/y (position)\n"
"# set_pose_state is true if the new pose service has been activated\n"
"float32 theta\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::rigid2d::set_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rigid2d::set_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rigid2d::set_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rigid2d::set_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIGID2D_MESSAGE_SET_POSEREQUEST_H
