// Generated by gencpp from file nuturtle_robot/startResponse.msg
// DO NOT EDIT!


#ifndef NUTURTLE_ROBOT_MESSAGE_STARTRESPONSE_H
#define NUTURTLE_ROBOT_MESSAGE_STARTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nuturtle_robot
{
template <class ContainerAllocator>
struct startResponse_
{
  typedef startResponse_<ContainerAllocator> Type;

  startResponse_()
    : direction_set(false)  {
    }
  startResponse_(const ContainerAllocator& _alloc)
    : direction_set(false)  {
  (void)_alloc;
    }



   typedef uint8_t _direction_set_type;
  _direction_set_type direction_set;





  typedef boost::shared_ptr< ::nuturtle_robot::startResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nuturtle_robot::startResponse_<ContainerAllocator> const> ConstPtr;

}; // struct startResponse_

typedef ::nuturtle_robot::startResponse_<std::allocator<void> > startResponse;

typedef boost::shared_ptr< ::nuturtle_robot::startResponse > startResponsePtr;
typedef boost::shared_ptr< ::nuturtle_robot::startResponse const> startResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nuturtle_robot::startResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nuturtle_robot::startResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nuturtle_robot::startResponse_<ContainerAllocator1> & lhs, const ::nuturtle_robot::startResponse_<ContainerAllocator2> & rhs)
{
  return lhs.direction_set == rhs.direction_set;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nuturtle_robot::startResponse_<ContainerAllocator1> & lhs, const ::nuturtle_robot::startResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nuturtle_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::startResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::startResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::startResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::startResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::startResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::startResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nuturtle_robot::startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a608a39707d4f244245bf8fb8322051c";
  }

  static const char* value(const ::nuturtle_robot::startResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa608a39707d4f244ULL;
  static const uint64_t static_value2 = 0x245bf8fb8322051cULL;
};

template<class ContainerAllocator>
struct DataType< ::nuturtle_robot::startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nuturtle_robot/startResponse";
  }

  static const char* value(const ::nuturtle_robot::startResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nuturtle_robot::startResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool direction_set\n"
"\n"
;
  }

  static const char* value(const ::nuturtle_robot::startResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nuturtle_robot::startResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction_set);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nuturtle_robot::startResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nuturtle_robot::startResponse_<ContainerAllocator>& v)
  {
    s << indent << "direction_set: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction_set);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUTURTLE_ROBOT_MESSAGE_STARTRESPONSE_H
