// Generated by gencpp from file nuturtle_robot/startRequest.msg
// DO NOT EDIT!


#ifndef NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H
#define NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nuturtle_robot
{
template <class ContainerAllocator>
struct startRequest_
{
  typedef startRequest_<ContainerAllocator> Type;

  startRequest_()
    : direction()  {
    }
  startRequest_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::nuturtle_robot::startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nuturtle_robot::startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct startRequest_

typedef ::nuturtle_robot::startRequest_<std::allocator<void> > startRequest;

typedef boost::shared_ptr< ::nuturtle_robot::startRequest > startRequestPtr;
typedef boost::shared_ptr< ::nuturtle_robot::startRequest const> startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nuturtle_robot::startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nuturtle_robot::startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nuturtle_robot::startRequest_<ContainerAllocator1> & lhs, const ::nuturtle_robot::startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nuturtle_robot::startRequest_<ContainerAllocator1> & lhs, const ::nuturtle_robot::startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nuturtle_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nuturtle_robot::startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nuturtle_robot::startRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nuturtle_robot::startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nuturtle_robot::startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::nuturtle_robot::startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::nuturtle_robot::startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nuturtle_robot/startRequest";
  }

  static const char* value(const ::nuturtle_robot::startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nuturtle_robot::startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# set the direction of the rotation\n"
"# direction is either clockwise or counter-clockwise\n"
"# set_pose_state is true when the direction is established \n"
"string direction\n"
;
  }

  static const char* value(const ::nuturtle_robot::startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nuturtle_robot::startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nuturtle_robot::startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nuturtle_robot::startRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUTURTLE_ROBOT_MESSAGE_STARTREQUEST_H
